---
# tasks file for ansible-role-ycsb

---
# Install and configure YCSB for MongoDB

- name: Set fact
  ansible.builtin.set_fact:
    user_dir: "{{ lookup('env','HOME') }}"

- name: Create ycsb directory
  ansible.builtin.file:
    path: "{{ user_dir }}/ycsb"
    state: directory
    mode: '0755'
  tags:
    - ycsb

# To Do: Need to check actual contents of file, not just that it's there
# to make sure we make changes if {{ dbsize }} gets updated between runs.
- name: Check for existing YCSB config
  ansible.builtin.stat:
    path: "{{ user_dir }}/ycsb/workloads/"
  register: ycsb_config

- name: Download and expand MongoDB YCSB bindings archive file to {{ user_dir }}/ycsb
  ansible.builtin.unarchive:
    src: ycsb-mongodb-binding-0.17.0.tar.gz
    dest: "{{ user_dir }}/ycsb"
    extra_opts:
      - --strip-components=1
  when: [
    - not ycsb_config.stat.exists
    - ycsb_bindings == 'mongodb'
    ]
  tags: [task_unarchive]

- name: Download and expand Cassandra YCSB bindings archive file to {{ user_dir }}/ycsb
  ansible.builtin.unarchive:
    src: ycsb-cassandra-binding-0.17.0.tar.gz
    dest: "{{ user_dir }}/ycsb"
    extra_opts:
      - --strip-components=1
  when: [
    - not ycsb_config.stat.exists
    - ycsb_bindings == 'cassandra'
    ]

  tags: [task_unarchive]

- name: Modify YCSB workloads/workloada file
  ansible.builtin.replace:
    path: "{{ user_dir }}/ycsb/workloads/workloada"
    regexp: '1000'
    replace: "{{ dbsize }}"
  tags: [task_unarchive]

- name: Copy YCSB load_db.sh file to host
  ansible.builtin.template:
    src: mongodb_ycsb_load_db.j2
    dest: "{{ user_dir }}/ycsb/ycsb_load_db.sh"
    mode: '0755'
  when: ycsb_bindings == 'mongodb'

- name: Copy YCSB ycsb_run_workload.sh file to host
  ansible.builtin.template:
    src: mongodb_ycsb_run_workload.j2
    dest: "{{ user_dir }}/ycsb/ycsb_run_workload.sh"
    mode: '0755'
  when: ycsb_bindings == 'mongodb'

- name: Configure update-alternatives for Python 2.7 (YCSB)
  community.general.alternatives:
    name: python
    path: /usr/bin/python2.7
    link: /usr/local/bin/python
    state: present

- name: Configure update-alternatives for Python 3
  community.general.alternatives:
    name: python
    path: /usr/bin/python3
    link: /usr/local/bin/python
    state: auto
